[install]
registry = "https://registry.npmjs.org/"

[install.scopes]
"@expo" = "https://registry.npmjs.org/"
"@react-native" = "https://registry.npmjs.org/"
"@typescript-eslint" = "https://registry.npmjs.org/"
"@tanstack" = "https://registry.npmjs.org/"